project_name: gautocloud

builds:
  - id: binary
    binary: gautocloud
    dir: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser={{.Env.USER}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      -
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - id: archives
    builds:
      - binary
    format: "tar.gz"
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true
  - id: archives-zip
    builds:
      - binary
    format: "zip"
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: orange-cloudfoundry
    name: gautocloud
  prerelease: auto
  name_template: '{{.Tag}}'
